apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: wso2-transport
  namespace: {{ .Release.Namespace }}
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wso2-am-route
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.kubernetes.ingress.management.hostname }}`)
      kind: Rule
      services:
        - name: {{ template "am-all-in-one.fullname" . }}-am-service
          port: 9443
          scheme: https
          serversTransport: wso2-transport
    - match: Host(`{{ .Values.kubernetes.ingress.gateway.hostname }}`)
      kind: Rule
      services:
        - name: {{ template "am-all-in-one.fullname" . }}-am-service
          port: 8243
          scheme: https
          serversTransport: wso2-transport
    - match: Host(`{{ .Values.kubernetes.ingress.websocket.hostname }}`)
      kind: Rule
      services:
        - name: {{ template "am-all-in-one.fullname" . }}-am-service
          port: 8243
          scheme: https
          serversTransport: wso2-transport
    - match: Host(`{{ .Values.kubernetes.ingress.websub.hostname }}`)
      kind: Rule
      services:
        - name: {{ template "am-all-in-one.fullname" . }}-am-service
          port: 8243
          scheme: https
          serversTransport: wso2-transport
  tls:
    secretName: wso2-tls-secret
