name: WSO2 APIM CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  helm-lint:
    name: Lint Helm Chart
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Helm chart
        run: helm lint helm/

  argocd-sync:
    name: Sync ArgoCD
    runs-on: self-hosted
    needs: helm-lint
    steps:
      - name: Sync ArgoCD App
        run: |
          argocd login 192.168.1.21 \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --insecure
          argocd app sync wso2-apim --insecure
